### ISSUE TITLE
Plasma contract reverting on deposit

### ISSUE THREAD

**Issue by lgalabru** [kyokan/plasma#53]
Hello there, me again :-).

When I run:

    plasma deposit --amount 10

The transaction is being rejected by the EVM.
When I comment the following checks, it works:

    function deposit(bytes txBytes) public payable {
        // var txItem = txBytes.toRLPItem();
        // var txList = txItem.toList();

        // var newOwnerIdx = 6;
        // var amountIdx = 7;
        // require(msg.sender == txList[newOwnerIdx].toAddress());
        // require(msg.value == txList[amountIdx].toUint());

Can you provide the documentation for `newOwnerIdx = 6` and `amountIdx =  7`? Should be `newOwnerIdx = 7` and `amountIdx =  8`, no?
When I look at the RLP encoding in the Golang implementation (transaction.go), or even the spec on ethersearch, I'm not sure to understand why we're taking those values, but I might be missing something. 
Thank you again for your work and your help!

**Comment by mslipper** [comment]
You are correct - the indices are wrong. We changed the data structure and didn't update the contract yet.

We're taking these values in order to ensure that the provided transaction's recipient and value match the method caller's sender and value.

By the way - I'd love to chat with you about how you're using our Plasma implementation. Would you mind shooting me an e-mail at mslipper@kyokan.io?

**Comment by mslipper** [comment]
This should be fixed now.

**Comment by lgalabru** [comment]
Indeed, thanks you for your help. The config file is also a great addition :).
